### PR TITLE
[WIP] Add tests for certain assumptions

### PR DESCRIPTION
**Pull request by bganglia**
Tests (and fixes to make them pass) were added for the following asumptions:
1. All files in images/ are referenced in metadata.csv (a number of unreferenced images deleted)
2. All patients are adults (2 pediatric patients removed)
3. No duplicate images (no change needed)

### CODE REVIEW

**Comment by ieee8023** [comment]
I think we should trace the source of the images instead of deleting them. Maybe we can add them to the metadata file with a to-do label?

I added the FAFA image as an image to remind people to look at the the metadata file.

**Comment by bganglia** [comment]
@ieee8023 Ok, I was able to trace the source of all images except for one, which I am still looking for.

The main sources are:
- Images deleted from the Hannover dataset (suggest to delete)
- Some COVID or MERS images that are missing annotation (suggest to annotate)
- Non-pneumonia images or X-ray closeups (suggest to delete)

Special cases:
 - The pediatric patients previously deleted in this PR (suggest to delete)
 - "Classic or possible" COVID? (suggest to annotate?)
 - One duplicate (suggest to delete)
 - The warning image should definitely be there, sorry!

All images:

Filename | Source | Proposed Action
-- | -- | --
000001-16.jpg | From https://www.eurorad.org/case/3397, appears to be unrelated | Delete
000001-5.jpg | Patient 401, pediatric | Delete
00cfd1c1.jpg | Deleted from Hannover | Delete
02b76460.jpg | Deleted from Hannover | Delete
1-s2.0-S2387020620301959-gr3_lrg-a.png | From this publication: https://www.sciencedirect.com/science/article/pii/S2387020620301959?via%3Dihub. At first appears to be a duplicate of 1-s2.0-S2387020620301959-gr4_lrg-a.png, but on closer inspection some differences are apparent. | Annotate
10.1016-slash-j.crad.2020.04.002-c.png | Non-covid diagnosis, only pleural effusion is specified (last image from https://www.clinicalradiologyonline.net/article/S0009-9260(20)30142-2/pdf) | Delete
289cb15b.jpg | Deleted from Hannover | Delete
6ed02c7c0f5f876f310e67e410e4fc_jumbo.jpeg | Small window of a larger X-ray | Delete
730a0b8f.jpg | Deleted from Hannover | Delete
7c0d0e1d.jpg | Deleted from Hannover | Delete
9eca9ade.jpg | Deleted from Hannover | Delete
FAFA-A1BF-49A8-A1D3-66FAFA41B7345D.jpg | Warning image | Keep!
MERS-CoV-1-s2.0-S0378603X1500248X-gr4e.jpg | From https://www.sciencedirect.com/science/article/pii/S0378603X1500248X, which appears to have a number of other images that could be added. | Delete
ansu-publish-ahead-of-print-10.1097.sla.0000000000003955-g001-a.png | From https://journals.lww.com/annalsofsurgery/FullText/2020/07000/Lung_Transplantation_for_Elderly_Patients_With.14.aspx | Annotate
ansu-publish-ahead-of-print-10.1097.sla.0000000000003955-g001-c.png | From https://journals.lww.com/annalsofsurgery/FullText/2020/07000/Lung_Transplantation_for_Elderly_Patients_With.14.aspx | Annotate
ansu-publish-ahead-of-print-10.1097.sla.0000000000003955-g001-d.png | From https://journals.lww.com/annalsofsurgery/FullText/2020/07000/Lung_Transplantation_for_Elderly_Patients_With.14.aspx | Annotate
ansu-publish-ahead-of-print-10.1097.sla.0000000000003955-g001-a.png | From https://journals.lww.com/annalsofsurgery/FullText/2020/07000/Lung_Transplantation_for_Elderly_Patients_With.14.aspx | Annotate
aqaa062i0002-a.png | From https://academic.oup.com/ajcp/article/153/6/725/5818922, but low-quality | Annotate
aqaa062i0002-b.png | From https://academic.oup.com/ajcp/article/153/6/725/5818922, but low-quality | Annotate
auntminnie-2020_01_31_20_24_2322_2020_01_31_x-ray_coronavirus_US.jpg | Appears to be a duplicate of nejmoa2001191_f5-PA.jpeg | Delete
cae2c0a9.jpg | Deleted from Hannover | Delete
ciaa199.pdf-001-c.png | Patient 62, pediatric | Delete
e22aa56f.jpg | Deleted from Hannover | Delete
eb8e8a5b.jpg | Deleted from Hannover | Delete
f0864aff.jpg | Deleted from Hannover | Delete
gr1_lrg.jpg | From https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7151400/?report=classic, but only "possible" COVID | Annotate?

I am still trying to find the source of ``radiopaedia-2019-novel-coronavirus-infected-pneumonia.jpg``. This image was added on March 5th, but I can't find it in the Radiopaedia cases published on/before that date. It is possible that the original case was deleted, since Radiopaedia has a ``covid-19-pneumonia-2`` case but no ``covid-19-pneumonia-1`` or ``covid-19-pneumonia``.

**Comment by ieee8023** [comment]
Why delete on MERS-CoV-1-s2.0-S0378603X1500248X-gr4e.jpg? 

When in doubt with gr1_lrg.jpg we can just call it Pneumonia

Ah it makes sense to remove radiopaedia-2019-novel-coronavirus-infected-pneumonia.jpg because the source page was likely removed.

Awesome work!

**Comment by bganglia** [comment]
You are right, MERS-CoV-1-s2.0-S0378603X1500248X-gr4e.jpg should have said "Annotate" (fixed now). Ok, so if it sounds all right to you I will
- keep the warning image and add the ones that say "Annotate" as "todo"
- and delete the other ones

**Comment by ieee8023** [comment]
Sounds good!

**Pull request merged**
