### PR TITLE
[WIP] Add https://radiopaedia.org/cases/covid-19-pneumonia-21

### LINKED ISSUE #52: https://radiopaedia.org/play/25975/entry/462501/case/75189/presentation?lang=us
Images on slides 2 and 3

### PR DESCRIPTION
**Pull request by bganglia**
This closes #52 

Radiopaedia did not specify a Creative Commons sub-license, so I chose "CC BY-NC-SA", because the other Radiopaedia images use that license.

### CODE REVIEW

**Comment by ieee8023** [comment]
You are missing file covid-19-pneumonia-rapidly-progressive.jpg right? 6 lines in the metadata file but 5 images.

**Comment by bganglia** [comment]
@ieee8023 Sorry, I started adding the new images to the same branch instead of a new one. Let me fix this.

**Comment by ieee8023** [comment]
No problem. If you want to fill up a branch and commit that would be easier I think. I won't commit anything else until tomorrow so it won't conflict any more than it already does.

**Comment by bganglia** [comment]
@ieee8023 Ok, I will do that. I will only make the PR after all of the articles from the batch have been added.

**Pull request closed without merging**
