### PR TITLE
Reconstructed images

### PR DESCRIPTION
**Pull request by m-zayan**
Reconstructed images, has extra information (more informative than the original images).

> #### Each cell corresponds to a specific feature, the cell 1 is channel 1, and it's the same for cells 2 and 3, the cell 4 is the reconstructed image (RGB).

sample_image_13

--------

sample_image

### CODE REVIEW

**Comment by ieee8023** [comment]
I don't understand what this is. Is there a paper that discusses what you are doing?

**Comment by m-zayan** [comment]
> I don't understand what this is. Is there a paper that discusses what you are doing?

It's an unpublished research algorithm, we are still working on it, I share the initial phase outputs, I guess it's quite interesting, and could be useful, I am going to try to summarize the output, the features have been decomposed over channels, those features selected by the algorithm, algorithm based on constrained optimization problem, the cell 4 on the first image is the reconstructed image, and the others is there channels, sorry but i need to be careful with details.

**Comment by ieee8023** [comment]
What is the use case for these images and the method? What value do you believe they can add to studying a cheat X-ray? I don't understand what the layers could represent.

**Comment by m-zayan** [comment]
> What is the use case for these images and the method? What value do you believe they can add to studying a cheat X-ray? I don't understand what the layers could represent.

I imagine that the 1st and 2nd channels could be used as segmented images, it's interesting that each of them care about some sort of pixel distribution, and the 3rd is the edges of the segmented image.  The output could be used as an alternative for the original images, I guess the reconstructed images quite interesting as it's not using any ground truth for optimization, it's quite same as clustering, so it's generalized very well for all 45 classes and the output could be more informative even we didn't use and extra models, it's could represent the latent distribution.

**Comment by ieee8023** [comment]
Ok, I'll close this for now because it doesn't fit into the scope of this dataset right now. It seems like this should belong it its own repository.

**Pull request closed without merging**
