### PR TITLE
Add the rest of the Radiopaedia data from 4/5/2020

### PR DESCRIPTION
**Pull request by bganglia**
Here, if a patient was ever intubated, I put "Intubated: Y" in all of the patient's images, even if some were from before intubation. Is this the correct decision here? I could not tell if the "intubated" column is at the patient or image level.

### CODE REVIEW

**Comment by ieee8023** [comment]
I tried to write it out in SCHEMA.md 
"Yes (Y) if the patient was intubated as some point during this illness or No (N) or blank if unknown"

I think this makes sense from the standpoint of severity prediction to grade how severe the situation became. The same goes for survival and  went_icu, needed_supplemental_O2, and extubated.

**Comment by bganglia** [comment]
@ieee8023 Thank you, that makes sense. I will check SCHEMA.md next time

**Comment by ieee8023** [comment]
I added more details to the SCHEMA.md. @Lan-Dao can fact check it.

**Comment by ieee8023** [comment]
Thinking more about it we should add a column like "intubation_present" so we can evaluate models on pre-intubation images. Otherwise, the model could just detect the tube.

**Comment by bganglia** [comment]
@ieee8023 That makes sense. I can work on that next.

What do you think about splitting the metadata into two tables, one with the image metadata (image ID as key) and one with the patient metadata (patient ID as key)? Maybe merging the two could be part of the dataloader, so that users would not have to do it themselves. On the other hand maybe it is better not to make things more complicated

**Comment by ieee8023** [comment]
I think a single CSV makes it very easy to work with for now. Maybe at 1000 images we can refactor. For some other data products that people can contribute like segmentations I think those could be separate and then joined because they are one time very specific attributes.

**Pull request merged**
