### PR TITLE
Changes typo in filenames

### PR DESCRIPTION
**Pull request by BeatrizGSC**

### CODE REVIEW

**Comment by ieee8023** [comment]
Thanks!

**Comment by ieee8023** [comment]
I added a test script in e5af693 to prevent this.

**Comment by BeatrizGSC** [comment]
There are some column names with spaces too like 'url '.

**Comment by ieee8023** [comment]
Fixed! Thanks!

**Comment by bganglia** [comment]
@ieee8023 What do you think about adding some tests to this repository directly? With Travis CI it could be set up so that there is a check with every update to the dataset.

I have gotten this working on one of my repositories and could add the code for it if you would like.

**Comment by ieee8023** [comment]
If it is not difficult that would be cool. I think collecting more data is a higher priority though.

**Pull request merged**
