### PR TITLE
Add Eurorad Images 5 15 2020

### LINKED ISSUE #72: https://www.eurorad.org/advanced-search?search=COVID
Eurorad has a very convenient collection of COVID-19 cases at the link above. These are the URLs with X-rays
- [ ] https://www.eurorad.org/case/16663
- [ ] https://www.eurorad.org/case/16660
- [ ] https://www.eurorad.org/case/16654
- [ ] https://www.eurorad.org/case/16691
- [ ] https://www.eurorad.org/case/16674
- [ ] https://www.eurorad.org/case/16672
- [ ] https://www.eurorad.org/case/16669
- [ ] https://www.eurorad.org/case/16664
There may still be some other cases floating around on Eurorad (e.g. Radiopaedia's "All COVID-19 cases" is not actually complete)

### PR DESCRIPTION
**Pull request by bganglia**
According to Eurorad's [Terms and Conditions](https://www.eurorad.org/terms-and-conditions), these images are all licensed under Creative Commons License CC BY-NC-SA 4.0.

Does "bedside Chest X-ray" equate to "supine"? I did not make that assumption here, but if it is correct, I could update some of the entries with that extra information.

This should close #72

### CODE REVIEW

**Comment by ieee8023** [comment]
I don't know if the bedside X-ray means supine. I can send an email to the eurorad team.

For the images I think there are much higher res on the site. I clicked one and went into the viewer and then right clicked to inspect element and was able to get a link to the high res version. I think I can script something to downloader higher res versions from this url: https://www.eurorad.org/sites/default/files/styles/figure_image/public/figure_image/2020-03/16654_2_1.jpg

I think for eurorad we should build a scraper to automate it. I committed one for radiopedia for CT scans in the scripts folder.

**Comment by ieee8023** [comment]
I just ran wget to get the higher res images. For some of them I needed to change the month the April.

**Comment by ieee8023** [comment]
For which one does it say "bedside Chest X-ray" ?

**Comment by bganglia** [comment]
Thanks! I didn't know about the higher-res images.

This is the case that said bedside X-ray in this batch:
https://www.eurorad.org/case/16674

There have been others earlier in the dataset, though.

**Comment by ieee8023** [comment]
From looking at it, it doesn't appear that they are laying down. So I would go with just regular AP.

**Pull request merged**
