### PR TITLE
Link to BSTI Covid-19 Radiographs

### PR DESCRIPTION
**Pull request by bganglia**
Here is another site we can scrape images from

### CODE REVIEW

**Comment by ieee8023** [comment]
I didn't want to list them because their terms are not clear. https://bsticovid19.cimar.co.uk/terms

Also, their interface seems hard to work with.

I emailed them again to ask if we can use it. I'll update this when I hear back.

**Comment by ieee8023** [comment]
They said "unfortunately these images are not available for distribution right now. However, we will update you as soon as that changes!"

**Comment by bganglia** [comment]
@ieee8023 That's too bad. I guess I will close this PR for now. Hopefully things will change

**Comment by ieee8023** [comment]
Another message from them:
"Whilst we would love to support the great work that you are doing, unfortunately the BSTI database does not have agreements in place to allow the data to be downloaded for research studies or any other use case. Should this change, I will be sure to reach out"

**Pull request closed without merging**
